language: cpp

compiler:
  - gcc

addons:
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.8']

env: COMPILER=g++-4.8


before_install:
    - sudo apt-get install libeigen3-dev
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo apt-get update
    - sudo apt-get install cmake-data
    - sudo apt-get install cmake

install:
    - mkdir build
    - cd build
    - cmake ../src
    - export CXX=$COMPILER
    - make

script:
    - make test ARGS="-V"
