before_install:
    - sudo apt-get install libeigen3-dev software-properties-common
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get upgrade
    - mkdir build
    - cd build
    - cmake ../src

install: make
language: cpp
compiler:
  - clang
  - gcc
